### ISSUE TITLE
Error in NeoPixel THT?

### ISSUE THREAD

**Issue by PaddyCube** [xdesig/NanoClon#2]
Hello,

Ifound an error with the board layout. I use some WS2812D-THT LEDs I' not able to control.
According to your documentation, the flat side of LED needs to be faced to the edge of PCB.
When it gots soldered in this place, 5V and GND are swapped. If I rotate by 180deg. DIN and DOUT are swapped, so it will not work this way.

So you either need to swap 5V and GND, or DOUT and DIN

According to Documentation, I placed the LED so that flat side faces to PCB edge
![20230526_122930](https://github.com/xdesig/NanoClon/assets/26644498/ce5a99e8-f995-4e16-9b46-449f81f93e6a)
This is the schematics I found for both, WS2811 and WS2812, the longest leg is VCC
![20230526_123041](https://github.com/xdesig/NanoClon/assets/26644498/54fc93d8-69df-4837-ab0b-6b96ebde8958)

Here you see that GND of LED is connected to VCC of shield
![20230526_123234](https://github.com/xdesig/NanoClon/assets/26644498/011b2bf9-0ebc-49a4-831a-5b969ea5fe61)

I'll try to solder a new LED and bending the pins.

Thanks so far for this cool project. My kids now can program their own robot and I've learned how to solder SMD

**Comment by xdesig** [comment]
I think you mean "You have found a problem with the Neopixel 5mm". When I
designed that board I made sure of the pins of those Neopixels. Now you can
find manufacturers that exchange pins, sorry for the inconvenience. The
neopixels that I have follow the Din, Vcc, GND, Dout norm

O ven., 26 de maio de 2023 ás 13:04, PaddyCube ***@***.***>)
escribiu:

**Comment by PaddyCube** [comment]
I'll close this issue. I solved it by swapping VCC and GND pin by bending before soldering. I assume you add some note to documentation so others are aware of this. Maybe you already added a note to spain description but at least me, I had to use google translate to understand.

**Comment by xdesig** [comment]
Hi Paddy.
We will be able to locate the most common neopixels now and do something to
fix this.
 Thank you.
 I would also like to translate the manual into English ( time to time)

Best regards
 Xabier Rosas

O dom., 28 de maio de 2023 ás 11:08, PaddyCube ***@***.***>)
escribiu:
